### ISSUE TITLE
'CompiledKernel' has no attribute 'launch_enter_hook'

### ISSUE THREAD

**Issue by zeropointnine** [woct0rdho/ComfyUI-RadialAttn#3]
Hi, I'm getting this error at the point when the Comfy workflow highlights the KSampler node:

> torch._inductor.exc.InductorError: AttributeError: type object 'CompiledKernel' has no attribute 'launch_enter_hook'

I'm using a 'minimal'  Windows non-portable (venv-based) comfy install, torch 2.7.1, cuda 12.8, gtx 4090, using your default workflow.

Relevant installed libs following the README instructions are:
```
triton-windows             3.4.0.post20
sageattention              2.2.0+cu128torch2.7.1.post1
spas_sage_attn             0.1.0+cu128torch2.7.1.post1
flashinfer-python          0.2.8
flash_attn                 2.7.4
```

Also, what are the required comfy command line flags? I'm currently using `--use-sage-attention`.

**Comment by J1mB091** [comment]
Downgrade triton-windows to 3.3.1

**Comment by woct0rdho** [comment]
Triton 3.4 only works with PyTorch >= 2.8 (for now it's pre-release, not officially released). You're using PyTorch 2.7 . You need to install Triton 3.3:
```pwsh
python -m pip install -U "triton-windows<3.4"
```

**Comment by zeropointnine** [comment]
Much appreciated. It's fully working now, thanks!
